spring.application.name=dmit2015-springboot-restapi
#Change the default web server port from 8080 to 8090
server.port=8090
# Change the context path from / to /restapi
spring.mvc.servlet.path=/restapi
