# Keycloak OpenID Connect configuration
# Use http://localhost:8180/realms/dmit2015-realm/.well-known/openid-configuration[OpenID Endpoint Configuration] to lookup the issuer.
keycloak.oidc.providerURI=http://localhost:8180/realms/dmit2015-realm/
keycloak.oidc.clientId=dmit2015-oracle-hr-demoapp
# You can find the Client secrets on the Credentials tab of the client details
keycloak.oidc.clientSecret=eflfmHYkYTXyRUtbUAiaGUc40HKFXJVG
keycloak.oidc.redirectURI=https://localhost:8443/callback
mp.jwt.verify.publickey.location=http://localhost:8180/realms/dmit2015-realm/protocol/openid-connect/certs
mp.jwt.verify.issuer=http://localhost:8180/realms/dmit2015-realm
