# Use http://localhost:8180/realms/dmit2015-realm/.well-known/openid-configuration[OpenID Endpoint Configuration] to lookup the issuer.
keycloak.oidc.providerURI=http://localhost:8180/realms/dmit2015-realm/
keycloak.oidc.clientId=yourJwtClient
# You can find the Client secrets on the Credentials tab of the client details
keycloak.oidc.clientSecret=yourJwtClientPassword